"""
This script runs a GUI which allows searching for desired features. 

All outputs generated by the llm are shown in a general text format, and are scrollable using the up/down arrow keys
or the left-hand scrollbar.

Tokens (text) are shown in a colormap indicating the activation level for the selected feature.

All feature activations may be visualized by using the mousewheel to scroll. 

A key-token, or muliple, may be highlighted/unhighlighted by left clicking them. This will limit the scrollable features to those
whose selected tokens fall above the activation threshold. Activation threshold can be set using the right-hand scrollbar.
"""


import csv
import pygame
from matplotlib import cm
import numpy as np


"""
LAYER 2, FEATURE 74: use of "None"
LAYER 18, FEATURE 156: the first token of a line inside a function or class
LAYER 19, FEATURE 746: convolutions on images, kernals

"""

# files
NPY_FILE = "all_features_out.npy"
CSV_FILE = "all_tokens_out.csv" 

ROW_PROMPT_INDEX = 0
ROW_TOKENS = 1

# feature layout
NUM_LAYERS = 24
NUM_FEATURES_PER_LAYER = 4096
FEATURE_COUNT = NUM_LAYERS * NUM_FEATURES_PER_LAYER


# window
WINDOW_W, WINDOW_H = 1400, 900
FPS = 60

FONT_NAME = None
FONT_SIZE = 18
LINE_SPACING = 4
MARGIN = 16

FEATURE_STEP_WHEEL = 1
FEATURE_STEP_WHEEL_FAST = 10

MIN_ALPHA = 0.06

# left scrollbar
SCROLLBAR_W = 14
SCROLLBAR_MARGIN = 8
SCROLLBAR_BG = (30, 30, 30)
SCROLLBAR_BORDER = (120, 120, 120)
SCROLLBAR_THUMB = (160, 160, 160)
SCROLLBAR_THUMB_HOVER = (190, 190, 190)
SCROLLBAR_THUMB_ACTIVE = (220, 220, 220)
SCROLLBAR_MIN_THUMB_H = 28

TEXT_X0 = MARGIN + SCROLLBAR_W + SCROLLBAR_MARGIN  # text starts to the right of the scrollbar

# histogram
HIST_W = 360
HIST_H = 220
HIST_MARGIN = 14
HIST_BINS = 40
HIST_BG = (12, 12, 12)
HIST_BORDER = (120, 120, 120)
HIST_TEXT = (230, 230, 230)
HIST_BAR = (200, 200, 200)
HIST_ZERO_LINE = (140, 140, 140)

# token highlight
HIGHLIGHT_BG = (100, 100, 100)
HIGHLIGHT_PAD_X = 3
HIGHLIGHT_PAD_Y = 2


# threshold slider
# selected features are those with activation > threshold for all highlighted tokens
THRESH_U8_INIT = 80  # 0>255
SLIDER_FILL_RED = (255, 40, 40)

# layer diagram styling
LAYER_BG = (80, 80, 80) 
LAYER_BORDER = (140, 140, 140)
LAYER_TEXT = (235, 235, 235)
LAYER_LINE = (255, 20, 20) 
LAYER_HIGHLIGHT = (20, 40, 170) 
LAYER_DIAG_MARGIN_TOP = 10
LAYER_RECT_H_MIN = 14

# slider styling - threshold (right side)
SLIDER_W = 14
SLIDER_THUMB_W = 32
SLIDER_BG = (26, 26, 26)
SLIDER_BORDER = (120, 120, 120)
SLIDER_THUMB = (170, 170, 170)
SLIDER_THUMB_HOVER = (195, 195, 195)
SLIDER_THUMB_ACTIVE = (225, 225, 225)
SLIDER_MIN_THUMB_H = 14

SLIDER_LABEL_COLOR = (230, 230, 230)


def clean_token(t: str) -> str:
    t = t.replace("Ġ", " ")
    t = t.replace("Ċ", "\n")
    return t


class Part:
    __slots__ = ("token_idx", "text", "x")
    def __init__(self, token_idx: int, text: str, x: int):
        self.token_idx = token_idx
        self.text = text
        self.x = x


class Line:
    __slots__ = ("parts", "y")
    def __init__(self, y: int):
        self.parts = []
        self.y = y


def split_token_preserve_newlines(tok: str):
    out = []
    buf = []
    for ch in tok:
        if ch == "\n":
            if buf:
                out.append("".join(buf))
                buf = []
            out.append("\n")
        else:
            buf.append(ch)
    if buf:
        out.append("".join(buf))
    return out


def build_wrapped_layout(font: pygame.font.Font, tokens, x0: int):
    max_w = WINDOW_W - x0 - MARGIN

    lines = []
    y = MARGIN
    line = Line(y=y)
    x = x0

    line_h = font.get_height()
    advance_y = line_h + LINE_SPACING

    for token_idx, tok in enumerate(tokens):
        segments = split_token_preserve_newlines(tok)

        for seg in segments:
            if seg == "\n":
                lines.append(line)
                y += advance_y
                line = Line(y=y)
                x = x0
                continue

            if seg == "":
                continue

            w = font.size(seg)[0]

            if x != x0 and x + w > x0 + max_w:
                lines.append(line)
                y += advance_y
                line = Line(y=y)
                x = x0

            line.parts.append(Part(token_idx=token_idx, text=seg, x=x))
            x += w

    lines.append(line)

    total_height = (lines[-1].y + (font.get_height() + LINE_SPACING) + MARGIN) if lines else WINDOW_H
    return lines, total_height


def clamp01(x: float) -> float:
    return 0.0 if x < 0.0 else (1.0 if x > 1.0 else x)


def activation_to_color(v: float, vmax: float):
    if vmax <= 0.0:
        a = 0.0
    else:
        a = v / vmax

    a = clamp01(a)

    if a > 0.0:
        a = MIN_ALPHA + (1.0 - MIN_ALPHA) * a

    r_f, g_f, b_f, _ = cm.viridis(a)
    return (int(r_f * 255), int(g_f * 255), int(b_f * 255))


def compute_histogram(values, bins: int):
    if values is None:
        return [0] * bins, 0.0, 1.0, 0, 0, 0

    if isinstance(values, np.ndarray):
        if values.size == 0:
            return [0] * bins, 0.0, 1.0, 0, 0, 0

        vmin = float(values.min())
        vmax = float(values.max())
        nonzero = int(np.count_nonzero(values))
        nonmax = int(np.count_nonzero(values == 255))

        if vmax <= vmin:
            counts = [0] * bins
            counts[0] = int(values.size)
            return counts, vmin, vmax, max(counts), nonzero, nonmax

        counts = [0] * bins
        span = 255#vmax - vmin

        for v in values.tolist():
            t = (v - vmin) / span
            if t <= 0.0:
                idx = 0
            elif t >= 1.0:
                idx = bins - 1
            else:
                idx = int(t * bins)
                if idx == bins:
                    idx = bins - 1
            counts[idx] += 1

        return counts, vmin, vmax, max(counts), nonzero, nonmax

    if not values:
        return [0] * bins, 0.0, 1.0, 0, 0, 0

    vmin = min(values)
    vmax = max(values)
    if vmax <= vmin:
        counts = [0] * bins
        counts[0] = len(values)
        nonzero = sum(1 for v in values if v != 0.0)
        nonmax = sum(1 for v in values if v != 255.0)
        return counts, vmin, vmax, max(counts), nonzero, nonmax

    counts = [0] * bins
    span = vmax - vmin
    for v in values:
        t = (v - vmin) / span
        if t <= 0.0:
            idx = 0
        elif t >= 1.0:
            idx = bins - 1
        else:
            idx = int(t * bins)
            if idx == bins:
                idx = bins - 1
        counts[idx] += 1

    nonzero = sum(1 for v in values if v != 0.0)
    nonmax = sum(1 for v in values if v != 255.0)
    return counts, vmin, vmax, max(counts), nonzero, nonmax


def draw_histogram(surface, rect, ui_font, counts, vmin, vmax, max_count, nonzero_count, nonmax_count, total_count):
    x, y, w, h = rect

    pygame.draw.rect(surface, HIST_BG, rect)
    pygame.draw.rect(surface, HIST_BORDER, rect, 1)

    inner_pad = 10
    title_h = ui_font.get_height() + 2
    footer_h = ui_font.get_height() * 2 + 6
    plot_x = x + inner_pad
    plot_y = y + inner_pad + title_h
    plot_w = w - 2 * inner_pad
    plot_h = h - 2 * inner_pad - title_h - footer_h

    title = ui_font.render("Activation histogram", True, HIST_TEXT)
    surface.blit(title, (x + inner_pad, y + inner_pad))

    if not counts or max_count <= 0 or plot_w <= 10 or plot_h <= 10:
        msg = ui_font.render("No data", True, HIST_TEXT)
        surface.blit(msg, (plot_x, plot_y))
        return

    base_y = plot_y + plot_h
    pygame.draw.line(surface, HIST_ZERO_LINE, (plot_x, base_y), (plot_x + plot_w, base_y), 1)

    bins = len(counts)
    bar_w = max(1, plot_w // bins)
    total_bars_w = bar_w * bins
    bar_x0 = plot_x + (plot_w - total_bars_w) // 2

    for i, c in enumerate(counts):
        if c <= 0:
            continue
        bh = int((c / max_count) * (plot_h - 1))
        bx = bar_x0 + i * bar_w
        by = base_y - bh
        pygame.draw.rect(surface, HIST_BAR, (bx, by, bar_w - 1, bh))

    z_pct = ((total_count-nonzero_count) / total_count) * 100.0 if total_count else 0.0
    m_pct = ((nonmax_count) / total_count) * 100.0 if total_count else 0.0
    line1 = f"zero: {z_pct:.2f}%, max: {m_pct:.2f}%"
    line2 = f"range: [{vmin/127.5:.2f}, {vmax/127.5:.2f}]"

    t1 = ui_font.render(line1, True, HIST_TEXT)
    t2 = ui_font.render(line2, True, HIST_TEXT)
    surface.blit(t1, (plot_x, plot_y + plot_h + 6))
    surface.blit(t2, (plot_x, plot_y + plot_h + 6 + ui_font.get_height() + 2))


def feature_to_layer_and_local(fid: int):
    fid = max(0, min(FEATURE_COUNT - 1, fid))
    layer = fid // NUM_FEATURES_PER_LAYER
    local = fid % NUM_FEATURES_PER_LAYER
    return layer, local


def draw_layer_diagram(surface, rect, ui_font, fid: int, eligible_features):
    x, y, w, h = rect

    pygame.draw.rect(surface, (16, 16, 16), rect)
    pygame.draw.rect(surface, HIST_BORDER, rect, 1)

    layer, local = feature_to_layer_and_local(fid)
    frac = 0.0 if NUM_FEATURES_PER_LAYER <= 1 else (local / (NUM_FEATURES_PER_LAYER - 1))

    pad = 8
    inner_x = x + pad
    inner_y = y + pad
    inner_w = w - 2 * pad
    inner_h = h - 2 * pad

    gap = 2
    rect_h = (inner_h - gap * (NUM_LAYERS - 1)) // NUM_LAYERS
    rect_h = max(LAYER_RECT_H_MIN, rect_h)

    total_needed = rect_h * NUM_LAYERS + gap * (NUM_LAYERS - 1)
    if total_needed > inner_h:
        rect_h = max(8, (inner_h - gap * (NUM_LAYERS - 1)) // NUM_LAYERS)

    start_y = inner_y

    line_x = inner_x + int(frac * max(0, inner_w - 1))
    line_x = max(inner_x, min(inner_x + inner_w - 1, line_x))

    for li in range(NUM_LAYERS):
        ry = start_y + li * (rect_h + gap)
        rrect = pygame.Rect(inner_x, ry, inner_w, rect_h)

        pygame.draw.rect(surface, LAYER_BG, rrect)
        pygame.draw.rect(surface, LAYER_BORDER, rrect, 1)

        # yellow markers are eligible features in this layer
        for f in eligible_features:
            if f // NUM_FEATURES_PER_LAYER != li:
                continue
            local_idx = f % NUM_FEATURES_PER_LAYER
            fx = 0.0 if NUM_FEATURES_PER_LAYER <= 1 else (local_idx / (NUM_FEATURES_PER_LAYER - 1))
            mx = rrect.x + int(fx * (rrect.w - 1))
            pygame.draw.line(
                surface,
                LAYER_HIGHLIGHT,
                (mx, rrect.y + 1),
                (mx, rrect.y + rrect.h - 2),
                1,
            )

        label = f"layer {li}"
        t = ui_font.render(label, True, LAYER_TEXT)
        surface.blit(t, (rrect.x + 6, rrect.y + (rrect.h - t.get_height()) // 2))

        if li == layer:
            pygame.draw.line(
                surface,
                LAYER_LINE,
                (line_x, rrect.y),
                (line_x, rrect.y + rrect.h - 1),
                3,
            )


def load_tokens_csv(csv_path: str):
    with open(csv_path, newline="", encoding="utf-8") as f:
        rows = list(csv.reader(f))

    if len(rows) < 2:
        raise RuntimeError("Token CSV must have at least 2 rows: prompt_index row and token row.")

    prompt_idx_row = rows[ROW_PROMPT_INDEX]
    token_row = rows[ROW_TOKENS]

    if len(token_row) < 2:
        raise RuntimeError("Token row is empty or missing header.")

    prompt_indices = prompt_idx_row[1:]
    tokens = token_row[1:]
    tokens = [clean_token(t) for t in tokens]

    return prompt_indices, tokens


def clamp(x, lo, hi):
    return lo if x < lo else (hi if x > hi else x)


def main():
    prompt_indices, tokens = load_tokens_csv(CSV_FILE)
    num_tokens = len(tokens)

    feature_data = np.load(NPY_FILE, mmap_mode="r")

    if feature_data.ndim != 2:
        raise RuntimeError(f"NPY must be 2D (features x tokens). Got shape={feature_data.shape}")
    if feature_data.shape[0] != FEATURE_COUNT:
        raise RuntimeError(f"NPY first dim must be {FEATURE_COUNT}. Got {feature_data.shape[0]}")
    if feature_data.shape[1] < num_tokens:
        raise RuntimeError(
            f"NPY has fewer token columns ({feature_data.shape[1]}) than token CSV ({num_tokens})"
        )

    if feature_data.shape[1] != num_tokens:
        num_tokens = min(num_tokens, feature_data.shape[1])
        tokens = tokens[:num_tokens]
        prompt_indices = prompt_indices[:num_tokens]

    pygame.init()
    pygame.display.set_caption("Feature Heatmap Viewer")
    screen = pygame.display.set_mode((WINDOW_W, WINDOW_H))
    clock = pygame.time.Clock()

    font = pygame.font.Font(FONT_NAME, FONT_SIZE)
    ui_font = pygame.font.Font(FONT_NAME, 16)

    lines, total_text_h = build_wrapped_layout(font, tokens, x0=TEXT_X0)
    max_scroll = max(0, total_text_h - WINDOW_H)
    scroll_y = 0

    highlighted_tokens = set()

    eligible_features = list(range(FEATURE_COUNT))
    feature_pos = 0

    activations = np.zeros((num_tokens,), dtype=np.uint8)
    vmax = 255.0

    hist_counts = [0] * HIST_BINS
    hist_vmin = 0.0
    hist_vmax = 255.0
    hist_maxc = 1
    hist_nonzero = 0
    hist_nonmax = 0

    # single slider-controlled value 
    thresh_u8 = int(clamp(int(THRESH_U8_INIT), 0, 255))

    line_h = font.get_height() + LINE_SPACING

    def y_to_line_index(y_px: int) -> int:
        return max(0, min(len(lines) - 1, (y_px - MARGIN) // line_h))

    def recompute_hist():
        nonlocal hist_counts, hist_vmin, hist_vmax, hist_maxc, hist_nonzero, hist_nonmax
        vals = activations.astype(np.float32)
        hist_counts, hist_vmin, hist_vmax, hist_maxc, hist_nonzero, hist_nonmax = compute_histogram(vals, HIST_BINS)
        if hist_maxc <= 0:
            hist_maxc = 1

    def current_feature_id():
        if not eligible_features:
            return 0
        return eligible_features[feature_pos]

    def load_feature_by_id(feature_id: int):
        nonlocal activations, vmax
        row_i = max(0, min(FEATURE_COUNT - 1, int(feature_id)))
        activations = np.asarray(feature_data[row_i, :num_tokens], dtype=np.uint8)
        vmax = float(activations.max()) if activations.size else 255.0
        if vmax <= 0.0:
            vmax = 1.0
        recompute_hist()

    def recompute_eligible_features():
        nonlocal eligible_features, feature_pos

        if not highlighted_tokens:
            eligible_features = list(range(FEATURE_COUNT))
            feature_pos = clamp(feature_pos, 0, len(eligible_features) - 1)
            return

        tok_list = np.array(sorted(highlighted_tokens), dtype=np.int64)
        tok_list = tok_list[(tok_list >= 0) & (tok_list < num_tokens)]
        if tok_list.size == 0:
            eligible_features = list(range(FEATURE_COUNT))
            feature_pos = clamp(feature_pos, 0, len(eligible_features) - 1)
            return

        sub = np.asarray(feature_data[:, tok_list], dtype=np.uint8) 
        keep_mask = np.all(sub > np.uint8(thresh_u8), axis=1)

        eligible_features = np.nonzero(keep_mask)[0].tolist()
        feature_pos = 0

    recompute_eligible_features()
    load_feature_by_id(current_feature_id())
    recompute_hist()

    hist_rect = (
        WINDOW_W - HIST_W - HIST_MARGIN,
        HIST_MARGIN,
        HIST_W,
        HIST_H,
    )

    # single vertical slider just to the left of the right side panel
    sliders_x0 = hist_rect[0] - SLIDER_W - 10
    sliders_y0 = HIST_MARGIN
    sliders_h = WINDOW_H - 2 * HIST_MARGIN
    slider_track = pygame.Rect(sliders_x0, sliders_y0, SLIDER_W, sliders_h) 

    diag_x = hist_rect[0]
    diag_y = hist_rect[1] + hist_rect[3] + LAYER_DIAG_MARGIN_TOP
    diag_w = hist_rect[2]
    diag_h = WINDOW_H - diag_y - HIST_MARGIN
    LAYER_INFO_H = ui_font.get_height() + 6

    layer_diag_rect = (
        diag_x,
        diag_y,
        diag_w,
        max(140, diag_h - LAYER_INFO_H),
    )


    # scrollbar state
    scroll_track_rect = pygame.Rect(MARGIN, MARGIN, SCROLLBAR_W, WINDOW_H - 2 * MARGIN)
    dragging_scroll = False
    drag_grab_offset_y = 0  # mouse_y - thumb_top when drag started

    def clamp_scroll(y: int) -> int:
        return clamp(y, 0, max_scroll)

    def thumb_height() -> int:
        if total_text_h <= 0:
            return scroll_track_rect.h
        vis = WINDOW_H
        frac = vis / total_text_h
        h = int(frac * scroll_track_rect.h)
        h = clamp(h, SCROLLBAR_MIN_THUMB_H, scroll_track_rect.h)
        return int(h)

    def scroll_to_thumb_y(scroll_val: int) -> int:
        if max_scroll <= 0:
            return scroll_track_rect.y
        track_y = scroll_track_rect.y
        track_h = scroll_track_rect.h
        th = thumb_height()
        travel = max(1, track_h - th)
        t = scroll_val / max_scroll
        return track_y + int(t * travel)

    def thumb_y_to_scroll(thumb_top_y: int) -> int:
        if max_scroll <= 0:
            return 0
        track_y = scroll_track_rect.y
        track_h = scroll_track_rect.h
        th = thumb_height()
        travel = max(1, track_h - th)
        thumb_top_y = clamp(thumb_top_y, track_y, track_y + travel)
        t = (thumb_top_y - track_y) / travel
        return int(t * max_scroll)

    def get_thumb_rect(scroll_val: int) -> pygame.Rect:
        th = thumb_height()
        ty = scroll_to_thumb_y(scroll_val)
        return pygame.Rect(scroll_track_rect.x, ty, scroll_track_rect.w, th)


    # lider helpers
    def slider_thumb_height(track_h: int) -> int:
        return clamp(int(track_h * 0.04), SLIDER_MIN_THUMB_H, track_h)


    def slider_value_to_thumb_top(track: pygame.Rect, value: float, vmin: float, vmax_: float) -> int:
        if vmax_ <= vmin:
            return track.y
        th = slider_thumb_height(track.h)
        travel = max(1, track.h - th)
        t = (value - vmin) / (vmax_ - vmin)
        t = clamp(t, 0.0, 1.0)
        return track.y + int((1.0 - t) * travel)

    def slider_thumb_top_to_value(track: pygame.Rect, thumb_top: int, vmin: float, vmax_: float) -> float:
        if vmax_ <= vmin:
            return vmin
        th = slider_thumb_height(track.h)
        travel = max(1, track.h - th)
        thumb_top = clamp(thumb_top, track.y, track.y + travel)
        t = 1.0 - ((thumb_top - track.y) / travel)
        return vmin + t * (vmax_ - vmin)

    def slider_get_thumb_rect(track: pygame.Rect, value: float, vmin: float, vmax_: float) -> pygame.Rect:
        th = slider_thumb_height(track.h)
        ty = slider_value_to_thumb_top(track, value, vmin, vmax_)

        # center a wider thumb over the narrow track
        thumb_x = track.centerx - SLIDER_THUMB_W // 2

        return pygame.Rect(thumb_x, ty, SLIDER_THUMB_W, th)

    dragging_slider = False
    slider_grab_offset = 0  # my - thumb.y at grab time

    clickable_rects = []

    def draw_slider(track: pygame.Rect, thumb: pygame.Rect, label_top: str, label_bottom: str, is_active: bool):
        pygame.draw.rect(screen, SLIDER_BG, track)

        # red fill (under handle)
        fill_top = max(track.y, min(track.bottom, thumb.bottom))
        if fill_top < track.bottom:
            pygame.draw.rect(
                screen,
                SLIDER_FILL_RED,
                pygame.Rect(track.x, fill_top, track.w, track.bottom - fill_top),
            )

        pygame.draw.rect(screen, SLIDER_BORDER, track, 1)

        mx, my = pygame.mouse.get_pos()
        hover = thumb.collidepoint(mx, my)
        if is_active:
            col = SLIDER_THUMB_ACTIVE
        elif hover:
            col = SLIDER_THUMB_HOVER
        else:
            col = SLIDER_THUMB

        pygame.draw.rect(screen, col, thumb)
        pygame.draw.rect(screen, SLIDER_BORDER, thumb, 1)

        t_top = ui_font.render(label_top, True, SLIDER_LABEL_COLOR)
        t_bot = ui_font.render(label_bottom, True, SLIDER_LABEL_COLOR)
        screen.blit(t_top, (track.x - 2, track.y - t_top.get_height() - 2))
        screen.blit(t_bot, (track.x - 2, track.y + track.h + 2))
        
    running = True
    while running:
        clock.tick(FPS)

        mx, my = pygame.mouse.get_pos()
        s_thumb = slider_get_thumb_rect(slider_track, float(thresh_u8), 0.0, 255.0)

        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False

            elif event.type == pygame.KEYDOWN:
                mods = pygame.key.get_mods()

                if event.key == pygame.K_ESCAPE:
                    running = False

                elif event.key == pygame.K_RIGHT:
                    step = 10 if (mods & pygame.KMOD_SHIFT) else 1
                    if eligible_features:
                        feature_pos = min(len(eligible_features) - 1, feature_pos + step)
                        load_feature_by_id(current_feature_id())

                elif event.key == pygame.K_LEFT:
                    step = 10 if (mods & pygame.KMOD_SHIFT) else 1
                    if eligible_features:
                        feature_pos = max(0, feature_pos - step)
                        load_feature_by_id(current_feature_id())

                elif event.key == pygame.K_PAGEDOWN:
                    if eligible_features:
                        feature_pos = min(len(eligible_features) - 1, feature_pos + 50)
                        load_feature_by_id(current_feature_id())

                elif event.key == pygame.K_PAGEUP:
                    if eligible_features:
                        feature_pos = max(0, feature_pos - 50)
                        load_feature_by_id(current_feature_id())

                elif event.key == pygame.K_HOME:
                    if eligible_features:
                        feature_pos = 0
                        load_feature_by_id(current_feature_id())

                elif event.key == pygame.K_END:
                    if eligible_features:
                        feature_pos = len(eligible_features) - 1
                        load_feature_by_id(current_feature_id())

            elif event.type == pygame.MOUSEWHEEL:
                mods = pygame.key.get_mods()
                step = FEATURE_STEP_WHEEL_FAST if (mods & pygame.KMOD_SHIFT) else FEATURE_STEP_WHEEL
                if eligible_features:
                    if event.y > 0:
                        feature_pos = max(0, feature_pos - step)
                        load_feature_by_id(current_feature_id())
                    elif event.y < 0:
                        feature_pos = min(len(eligible_features) - 1, feature_pos + step)
                        load_feature_by_id(current_feature_id())

            elif event.type == pygame.MOUSEBUTTONDOWN:
                if event.button == 1:
                    mx, my = event.pos

                    # slider interaction first
                    if slider_track.collidepoint(mx, my):
                        if s_thumb.collidepoint(mx, my):
                            dragging_slider = True
                            slider_grab_offset = my - s_thumb.y
                        else:
                            th = slider_thumb_height(slider_track.h)
                            desired_top = my - th // 2
                            new_val = slider_thumb_top_to_value(slider_track, desired_top, 0.0, 255.0)
                            new_u8 = int(round(clamp(new_val, 0.0, 255.0)))
                            if new_u8 != thresh_u8:
                                thresh_u8 = new_u8
                                recompute_eligible_features()
                                if eligible_features:
                                    load_feature_by_id(current_feature_id())
                                else:
                                    activations = np.zeros((num_tokens,), dtype=np.uint8)
                                    vmax = 255.0
                                    recompute_hist()

                    # scrollbar interactions
                    elif scroll_track_rect.collidepoint(mx, my) and max_scroll > 0:
                        thumb_rect = get_thumb_rect(scroll_y)
                        if thumb_rect.collidepoint(mx, my):
                            dragging_scroll = True
                            drag_grab_offset_y = my - thumb_rect.y
                        else:
                            th = thumb_height()
                            desired_top = my - th // 2
                            scroll_y = clamp_scroll(thumb_y_to_scroll(desired_top))

                    else:
                        # token click toggles highlight
                        clicked_tok = None
                        for rect, tid in clickable_rects:
                            if rect.collidepoint(mx, my):
                                clicked_tok = tid
                                break
                        if clicked_tok is not None:
                            if clicked_tok in highlighted_tokens:
                                highlighted_tokens.remove(clicked_tok)
                            else:
                                highlighted_tokens.add(clicked_tok)

                            prev_feature = current_feature_id() if eligible_features else None
                            recompute_eligible_features()

                            if not eligible_features:
                                activations = np.zeros((num_tokens,), dtype=np.uint8)
                                vmax = 255.0
                                recompute_hist()
                            else:
                                if prev_feature is not None and prev_feature in eligible_features:
                                    feature_pos = eligible_features.index(prev_feature)
                                else:
                                    feature_pos = 0
                                load_feature_by_id(current_feature_id())

            elif event.type == pygame.MOUSEBUTTONUP:
                if event.button == 1:
                    dragging_scroll = False
                    dragging_slider = False

            elif event.type == pygame.MOUSEMOTION:
                if dragging_scroll and max_scroll > 0:
                    mx, my = event.pos
                    th = thumb_height()
                    desired_top = my - drag_grab_offset_y
                    track_y = scroll_track_rect.y
                    travel = max(1, scroll_track_rect.h - th)
                    desired_top = clamp(desired_top, track_y, track_y + travel)
                    scroll_y = clamp_scroll(thumb_y_to_scroll(desired_top))

                if dragging_slider:
                    mx, my = event.pos
                    th = slider_thumb_height(slider_track.h)
                    desired_top = my - slider_grab_offset
                    travel = max(1, slider_track.h - th)
                    desired_top = clamp(desired_top, slider_track.y, slider_track.y + travel)
                    new_val = slider_thumb_top_to_value(slider_track, desired_top, 0.0, 255.0)
                    new_u8 = int(round(clamp(new_val, 0.0, 255.0)))
                    if new_u8 != thresh_u8:
                        thresh_u8 = new_u8
                        recompute_eligible_features()
                        if eligible_features:
                            load_feature_by_id(current_feature_id())
                        else:
                            activations = np.zeros((num_tokens,), dtype=np.uint8)
                            vmax = 255.0
                            recompute_hist()

        # ------------- draw ------------------
        screen.fill((20, 20, 20))

        # left text scrollbar
        pygame.draw.rect(screen, SCROLLBAR_BG, scroll_track_rect)
        pygame.draw.rect(screen, SCROLLBAR_BORDER, scroll_track_rect, 1)

        thumb_rect = get_thumb_rect(scroll_y)
        if max_scroll <= 0:
            thumb_col = SCROLLBAR_THUMB
        elif dragging_scroll:
            thumb_col = SCROLLBAR_THUMB_ACTIVE
        elif thumb_rect.collidepoint(pygame.mouse.get_pos()):
            thumb_col = SCROLLBAR_THUMB_HOVER
        else:
            thumb_col = SCROLLBAR_THUMB

        pygame.draw.rect(screen, thumb_col, thumb_rect)
        pygame.draw.rect(screen, SCROLLBAR_BORDER, thumb_rect, 1)

        # single right side slider
        s_thumb = slider_get_thumb_rect(slider_track, float(thresh_u8), 0.0, 255.0)
        draw_slider(
            slider_track,
            s_thumb,
            f"{(thresh_u8 / 127.5):.2f}",
            "threshold",
            dragging_slider,
        )

        # visible text window computation
        top_y = scroll_y
        bottom_y = scroll_y + WINDOW_H
        first_line = y_to_line_index(top_y + MARGIN)
        last_line = y_to_line_index(bottom_y + MARGIN + (font.get_height() + LINE_SPACING))

        clickable_rects = []

        for li in range(first_line, last_line + 1):
            if li < 0 or li >= len(lines):
                continue
            line = lines[li]
            draw_y = line.y - scroll_y
            if draw_y < -(font.get_height() + LINE_SPACING) or draw_y > WINDOW_H + (font.get_height() + LINE_SPACING):
                continue

            for part in line.parts:
                txt = part.text
                if txt == "":
                    continue
                w, h = font.size(txt)
                rect = pygame.Rect(part.x, draw_y, w, h)
                clickable_rects.append((rect, part.token_idx))

                if part.token_idx in highlighted_tokens:
                    bg = pygame.Rect(
                        rect.x - HIGHLIGHT_PAD_X,
                        rect.y - HIGHLIGHT_PAD_Y,
                        rect.w + 2 * HIGHLIGHT_PAD_X,
                        rect.h + 2 * HIGHLIGHT_PAD_Y,
                    )
                    pygame.draw.rect(screen, HIGHLIGHT_BG, bg)

                v = float(activations[part.token_idx]) if 0 <= part.token_idx < activations.size else 0.0
                color = activation_to_color(v, vmax)
                surf = font.render(txt, True, color)
                screen.blit(surf, (part.x, draw_y))

        # UI text under layer diagram
        if eligible_features:
            fid = current_feature_id()
            layer, local = feature_to_layer_and_local(fid)
            right_label = f"layer {layer}, feature {local}"
        else:
            right_label = "layer -, feature -"

        left_label = f"{len(eligible_features)} filtered features"

        left_surf = ui_font.render(left_label, True, (230, 230, 230))
        right_surf = ui_font.render(right_label, True, (230, 230, 230))

        info_y = layer_diag_rect[1] + layer_diag_rect[3] + 2
        screen.blit(left_surf, (layer_diag_rect[0], info_y))
        screen.blit(
            right_surf,
            (layer_diag_rect[0] + layer_diag_rect[2] - right_surf.get_width(), info_y),
        )

        draw_histogram(
            screen,
            hist_rect,
            ui_font,
            hist_counts,
            hist_vmin,
            hist_vmax,
            hist_maxc,
            hist_nonzero,
            hist_nonmax,
            num_tokens,
        )

        if eligible_features:
            draw_layer_diagram(
                screen,
                layer_diag_rect,
                ui_font,
                current_feature_id(),
                eligible_features,
            )
        else:
            draw_layer_diagram(screen, layer_diag_rect, ui_font, 0, [])

        pygame.display.flip()

    pygame.quit()


if __name__ == "__main__":
    main()
